// DO NOT EDIT THIS FILE!
// It is generated by `light` tool by source `model.go` at 2017-03-22 16:26:38.

package mapper

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/arstd/light/example/enum"
	"github.com/arstd/light/example/model"
	"github.com/arstd/log"
	"github.com/lib/pq"
)

type ModelMapperImpl struct{}

func (*ModelMapperImpl) Insert(trans *sql.Tx, m *model.Model) (err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` insert into models(name, flag, score, map, time, xarray, slice, status, pointer, struct_slice, uint32) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) returning id`)
	zmMap, _ := json.Marshal(m.Map)
	zmPointer, _ := json.Marshal(m.Pointer)
	zmStructSlice, _ := json.Marshal(m.StructSlice)
	xargs = append(xargs, m.Name, m.Flag, m.Score, zmMap, m.Time, pq.Array(m.Array), pq.Array(m.Slice), m.Status, zmPointer, zmStructSlice, m.Uint32)

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	xdest := []interface{}{&m.Id}
	err = db.QueryRow(xquery, xargs...).Scan(xdest...)
	if err != nil {
		log.Error(err)
		log.Error(xquery)
		log.Error(xargs...)
		return
	}
	return
}

func (*ModelMapperImpl) BatchInsert(tx *sql.Tx, ms []*model.Model) (xa int64, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` insert into models(uint32, name, flag, score, map, time, xarray, slice, status, pointer, struct_slice) values`)
	xargs = append(xargs)
	for i, m := range ms {
		if i != 0 {
			xbuf.WriteString(",")
		}
		xbuf.WriteString(` (%s+888, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)`)
		zmMap, _ := json.Marshal(m.Map)
		zmPointer, _ := json.Marshal(m.Pointer)
		zmStructSlice, _ := json.Marshal(m.StructSlice)
		xargs = append(xargs, i, m.Name, m.Flag, m.Score, zmMap, m.Time, pq.Array(m.Array), pq.Array(m.Slice), m.Status, zmPointer, zmStructSlice)
	}

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	xres, err := db.Exec(xquery, xargs...)
	if err != nil {
		log.Error(xquery)
		log.Error(xargs...)
		log.Error(err)
	}
	return xres.RowsAffected()
}

func (*ModelMapperImpl) Get(tx *sql.Tx, id int) (xobj *model.Model, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` select id, name, flag, score, map, time, xarray, slice, status, pointer, struct_slice, uint32 from models where id=%s`)
	xargs = append(xargs, id)

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	xobj = &model.Model{}
	var xobjzMap []byte
	var xobjzTime pq.NullTime
	var xobjzPointer []byte
	var xobjzStructSlice []byte
	xdest := []interface{}{&xobj.Id, &xobj.Name, &xobj.Flag, &xobj.Score, &xobjzMap, &xobjzTime, pq.Array(&xobj.Array), pq.Array(&xobj.Slice), &xobj.Status, &xobjzPointer, &xobjzStructSlice, &xobj.Uint32}
	err = db.QueryRow(xquery, xargs...).Scan(xdest...)
	if err != nil {
		log.Error(err)
		log.Error(xquery)
		log.Error(xargs...)
		return
	}
	xobj.Map = map[string]interface{}{}
	json.Unmarshal(xobjzMap, xobj.Map)
	xobj.Time = xobjzTime.Time
	xobj.Pointer = &model.Model{}
	json.Unmarshal(xobjzPointer, &xobj.Pointer)
	xobj.StructSlice = []*model.Model{}
	json.Unmarshal(xobjzStructSlice, &xobj.StructSlice)
	return
}

func (*ModelMapperImpl) Update(tx *sql.Tx, m *model.Model) (xa int64, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` update models set name=%s, flag=%s, score=%s, map=%s, time=%s, slice=%s, status=%s, pointer=%s, struct_slice=%s, uint32=%s where id=%s`)
	zmMap, _ := json.Marshal(m.Map)
	zmPointer, _ := json.Marshal(m.Pointer)
	zmStructSlice, _ := json.Marshal(m.StructSlice)
	xargs = append(xargs, m.Name, m.Flag, m.Score, zmMap, m.Time, pq.Array(m.Slice), m.Status, zmPointer, zmStructSlice, m.Uint32, m.Id)

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	xres, err := db.Exec(xquery, xargs...)
	if err != nil {
		log.Error(xquery)
		log.Error(xargs...)
		log.Error(err)
	}
	return xres.RowsAffected()
}

func (*ModelMapperImpl) Delete(tx *sql.Tx, id int) (xa int64, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` delete from models where id=%s`)
	xargs = append(xargs, id)

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	xres, err := db.Exec(xquery, xargs...)
	if err != nil {
		log.Error(xquery)
		log.Error(xargs...)
		log.Error(err)
	}
	return xres.RowsAffected()
}

func (*ModelMapperImpl) Count(tx *sql.Tx, m *model.Model, ss []enum.Status) (xcnt int64, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` select count(*) from models where name like %s`)
	xargs = append(xargs, m.Name)
	if m.Flag != false {
		xbuf.WriteString(` and flag=%s`)
		xargs = append(xargs, m.Flag)
	}
	if len(ss) != 0 {
		xargs = append(xargs)
		xbuf.WriteString(` and status in (`)
		xargs = append(xargs)
		for i, v := range ss {
			if i != 0 {
				xbuf.WriteString(",")
			}
			xbuf.WriteString(` %s`)
			xargs = append(xargs, v)
		}
		xbuf.WriteString(` )`)
		xargs = append(xargs)
	}
	if len(m.Slice) != 0 {
		xbuf.WriteString(` and slice && %s`)
		xargs = append(xargs, pq.Array(m.Slice))
	}

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	err = db.QueryRow(xquery, xargs...).Scan(&xcnt)
	if err != nil {
		log.Error(err)
		log.Error(xquery)
		log.Error(xargs...)
	}
	return
}

func (*ModelMapperImpl) List(tx *sql.Tx, m *model.Model, ss []enum.Status, offset int, limit int) (xdata []*model.Model, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` select id, name, flag, score, map, time, xarray, slice, status, pointer, struct_slice, uint32 from models where name like %s`)
	xargs = append(xargs, m.Name)
	if m.Flag != false {
		xargs = append(xargs)
		if len(ss) != 0 {
			xargs = append(xargs)
			xbuf.WriteString(` and status in (`)
			xargs = append(xargs)
			for i, v := range ss {
				if i != 0 {
					xbuf.WriteString(",")
				}
				xbuf.WriteString(` %s`)
				xargs = append(xargs, v)
			}
			xbuf.WriteString(` )`)
			xargs = append(xargs)
		}
		xbuf.WriteString(` and flag=%s`)
		xargs = append(xargs, m.Flag)
	}
	if len(m.Array) != 0 {
		xargs = append(xargs)
		xbuf.WriteString(` and xarray && array[`)
		xargs = append(xargs)
		for i, v := range m.Array {
			if i != 0 {
				xbuf.WriteString(",")
			}
			xbuf.WriteString(` %s`)
			zv, _ := json.Marshal(v)
			xargs = append(xargs, zv)
		}
		xbuf.WriteString(` ]`)
		xargs = append(xargs)
	}
	if len(m.Slice) != 0 {
		xbuf.WriteString(` and slice && %s`)
		xargs = append(xargs, pq.Array(m.Slice))
	}
	xbuf.WriteString(` order by id offset %s limit %s`)
	xargs = append(xargs, offset, limit)

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	log.Debug(xquery)
	log.Debug(xargs...)

	var xrows *sql.Rows
	xrows, err = db.Query(xquery, xargs...)
	if err != nil {
		log.Error(err)
		log.Error(xquery)
		log.Error(xargs...)
		return
	}
	defer xrows.Close()

	xdata = []*model.Model{}
	for xrows.Next() {
		xe := &model.Model{}
		xdata = append(xdata, xe)
		var xezMap []byte
		var xezTime pq.NullTime
		var xezPointer []byte
		var xezStructSlice []byte
		xdest := []interface{}{&xe.Id, &xe.Name, &xe.Flag, &xe.Score, &xezMap, &xezTime, pq.Array(&xe.Array), pq.Array(&xe.Slice), &xe.Status, &xezPointer, &xezStructSlice, &xe.Uint32}
		err = xrows.Scan(xdest...)
		if err != nil {
			log.Error(err)
			return
		}
		xe.Map = map[string]interface{}{}
		json.Unmarshal(xezMap, xe.Map)
		xe.Time = xezTime.Time
		xe.Pointer = &model.Model{}
		json.Unmarshal(xezPointer, &xe.Pointer)
		xe.StructSlice = []*model.Model{}
		json.Unmarshal(xezStructSlice, &xe.StructSlice)
	}
	if err = xrows.Err(); err != nil {
		log.Error(err)
		return
	}
	return
}

func (*ModelMapperImpl) Page(tx *sql.Tx, m *model.Model, ss []enum.Status, offset int, limit int) (xcnt int64, xdata []*model.Model, err error) {
	var (
		xbuf  bytes.Buffer
		xargs []interface{}
	)
	xbuf.WriteString(` select id, name, flag, score, map, time, slice, status, pointer, struct_slice from models where name like %s`)
	xargs = append(xargs, m.Name)
	if m.Flag != false {
		xargs = append(xargs)
		if len(ss) != 0 {
			xargs = append(xargs)
			xbuf.WriteString(` and status in (`)
			xargs = append(xargs)
			for i, v := range ss {
				if i != 0 {
					xbuf.WriteString(",")
				}
				xbuf.WriteString(` %s`)
				xargs = append(xargs, v)
			}
			xbuf.WriteString(` )`)
			xargs = append(xargs)
		}
		xbuf.WriteString(` and flag=%s`)
		xargs = append(xargs, m.Flag)
	}
	if len(m.Slice) != 0 {
		xbuf.WriteString(` and slice && %s`)
		xargs = append(xargs, pq.Array(m.Slice))
	}
	xbuf.WriteString(` order by id offset %s limit %s`)
	xargs = append(xargs, offset, limit)

	xholder := make([]interface{}, len(xargs))
	for i := range xargs {
		xholder[i] = fmt.Sprintf("$%d", i+1)
	}
	xquery := fmt.Sprintf(xbuf.String(), xholder...)
	xfindex := strings.LastIndex(xquery, " from ")
	xobindex := strings.LastIndex(xquery, "order by")
	xtquery := `select count(*)` + xquery[xfindex:xobindex]
	xdcnt := strings.Count(xquery[xobindex:], "$")
	xtargs := xargs[:len(xargs)-xdcnt]
	log.Debug(xtquery)
	log.Debug(xtargs...)

	err = db.QueryRow(xtquery, xtargs...).Scan(&xcnt)
	if err != nil {
		log.Error(err)
		log.Error(xquery)
		log.Error(xargs...)
	}
	if xcnt == 0 {
		return
	}

	log.Debug(xquery)
	log.Debug(xargs...)

	var xrows *sql.Rows
	xrows, err = db.Query(xquery, xargs...)
	if err != nil {
		log.Error(err)
		log.Error(xquery)
		log.Error(xargs...)
		return
	}
	defer xrows.Close()

	xdata = []*model.Model{}
	for xrows.Next() {
		xe := &model.Model{}
		xdata = append(xdata, xe)
		var xezMap []byte
		var xezTime pq.NullTime
		var xezPointer []byte
		var xezStructSlice []byte
		xdest := []interface{}{&xe.Id, &xe.Name, &xe.Flag, &xe.Score, &xezMap, &xezTime, pq.Array(&xe.Slice), &xe.Status, &xezPointer, &xezStructSlice}
		err = xrows.Scan(xdest...)
		if err != nil {
			log.Error(err)
			return
		}
		xe.Map = map[string]interface{}{}
		json.Unmarshal(xezMap, xe.Map)
		xe.Time = xezTime.Time
		xe.Pointer = &model.Model{}
		json.Unmarshal(xezPointer, &xe.Pointer)
		xe.StructSlice = []*model.Model{}
		json.Unmarshal(xezStructSlice, &xe.StructSlice)
	}
	if err = xrows.Err(); err != nil {
		log.Error(err)
		return
	}
	return
}
