package generator

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"

	"github.com/arstd/light/goparser"
)

func writeHeader(store *goparser.Store) *bytes.Buffer {
	var header bytes.Buffer

	w := header.WriteString
	wln := func(s string) { header.WriteString(s + "\n") }

	wln("// !!! DO NOT EDIT THIS FILE. It is generated by `light` tool.")
	wln("// @light: https://github.com/arstd/light")

	file := store.Source
	gopath := os.Getenv("GOPATH")
	for _, v := range strings.Split(gopath, string(filepath.ListSeparator)) {
		if strings.HasPrefix(file, v) {
			file = file[len(v)+5:]
		}
	}
	wln("// Generate from source: " + file)
	w("package ")
	wln(store.Package)
	wln(`import (
		"bytes"
		"fmt"
		"github.com/arstd/light/null"`)
	if store.Log {
		wln(`"github.com/arstd/log"`)
	}
	for k, v := range store.Imports {
		w(v)
		w(` "`)
		w(k)
		wln(`"`)
	}
	wln(")")

	w("type ")
	w(store.Name)
	wln("Store struct{}")

	return &header
}
