package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/arstd/light/goparser"
)

func writeHeader(store *goparser.Store) *bytes.Buffer {
	var header bytes.Buffer

	w := header.WriteString
	wln := func(s string) { header.WriteString(s + "\n") }

	wln("// !!! DO NOT EDIT THIS FILE. It is generated by `light` tool.")
	wln("// @light: https://github.com/arstd/light")

	file := store.Source
	gopath := os.Getenv("GOPATH")
	for _, v := range strings.Split(gopath, string(filepath.ListSeparator)) {
		if strings.HasPrefix(file, v) {
			file = file[len(v)+5:]
		}
	}
	wln("// Generated from source: " + file)
	w("package ")
	wln(store.Package)
	wln(`import (
		"bytes"
		"fmt"
		"github.com/arstd/light/light"
		"github.com/arstd/light/null"`)
	if store.Log {
		wln(`"github.com/arstd/log"`)
	}
	for k, v := range store.Imports {
		w(v)
		w(` "`)
		if i := strings.Index(k, "/vendor/"); i > 0 {
			w(k[i+8:])
		} else {
			w(k)
		}
		wln(`"`)
	}
	wln(")")

	name := store.Name
	if name[0] == 'I' {
		name = name[1:]
		fmt.Fprintf(&header, "func init(){ %s = new(Store%s)}\n", name, name)
	} else {
		fmt.Fprintf(&header, "func init(){ Default%s = new(Store%s)}\n", name, name)
	}
	fmt.Fprintf(&header, "type Store%s struct{}\n", name)

	return &header
}
